namespace Proyecto_Final____Sistema_de_Gestión_de_Clínica_Veterinaria
{
    public partial class Sistema_de_Gestión_Veterinaria_JOSE_PARDO : Form
    {
        public Sistema_de_Gestión_Veterinaria_JOSE_PARDO()
        {
            InitializeComponent();
        }

        private void Sistema_de_Gestión_Veterinaria_JOSE_PARDO_Load(object sender, EventArgs e)
        {

        }

        private void label1_Click(object sender, EventArgs e)
        {

        }

        private void btnPacientes_Click(object sender, EventArgs e)
        {
            
        }
    }


}
